In [1]:
from SimpleNet import*

In [2]:
train_set, test_set = prepare_dataset_iris("/Users/rui.zhong/SimpleNet/iris.data")

centers = compute_coco_center(train_set)
print(centers)

{'[ 0.  0.  1.]': array([ 0.70560265,  0.31813428,  0.59502476,  0.21647398], dtype=float32), '[ 0.  1.  0.]': array([ 0.74735892,  0.34958595,  0.53987861,  0.1666595 ], dtype=float32), '[ 1.  0.  0.]': array([ 0.8026275 ,  0.54710418,  0.23437415,  0.03917793], dtype=float32)}


In [3]:
net = Network([4, 3], learn_rate=0.03, loss_func=congenerous_cosine_func, centers=centers)

In [4]:
print(net.layers[-1].centers)

{'[ 0.  0.  1.]': array([ 0.70560265,  0.31813428,  0.59502476,  0.21647398], dtype=float32), '[ 0.  1.  0.]': array([ 0.74735892,  0.34958595,  0.53987861,  0.1666595 ], dtype=float32), '[ 1.  0.  0.]': array([ 0.8026275 ,  0.54710418,  0.23437415,  0.03917793], dtype=float32)}


In [5]:
net.train(train_set[0][:-1], train_set[0][-1])

ValueError: operands could not be broadcast together with shapes (3,) (4,) (3,) 

In [10]:
layer = net.layers[-1]
layer.centers
center_matrix = []
for center in sorted(layer.centers.keys()):
    center_matrix.append(layer.centers[center])
center_matrix = np.transpose(np.asarray(center_matrix, dtype=np.float32))
print(np.dot(center_matrix, layer.output - train_set[0][-1]))
print(layer.delta)
print(layer.weight)

[ 5.05000687  2.56971645  3.3966918   1.09109068]
[ 0.  0.  0.]
[[ 1.26016158 -0.47358908 -0.91854444]
 [ 0.36082855 -1.20672806 -0.656546  ]
 [-0.27867805  0.25933068 -0.07609545]
 [-0.14589484  0.19201003 -0.36095576]]
